### ISSUE TITLE
pound 2.7d - wrong url encoding with RedirectAppend 

### ISSUE THREAD

**Issue by irosaurus** [goochjj/pound#10]
Hi guys,

I'm running:
    Version 2.7d+github on Debian Wheezy
      Configuration switches:
        --with-ssl=yes
        --with-maxbuf=8192
        --with-owner=pound
        --with-group=pound

(Makefile slightly changed to create a 4096 dh.pem). 

I just tried to redirect all traffic to https and like in issue #3 the url encoding isn't working properly. 

This is my pound config:

```
Service "my.url.com"
    HeadRequire "^Host:[\t ].*my\.url\.com"
    RedirectAppend  "https://my.url.com/"
End
```

And if it is active, the redirect in my lighttpd log looks like this:
my.url.com - [10/Nov/2014:14:41:21 +0100] "GET /this%2dis%2dan%2dexample%2dlink/  HTTP/1.1" 404 20023 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0"

My blog displays an internal error 404 (not the webserver!), that there was a mistake and the site could not be found, although the link in the url bar looks fine: "https://my.url.com/this-is-an-example-link/". If I press F5, the page reloads with the same error. But if I click into the url bar and press enter, the side loads fine with https.

Looks like "-" is translated to "%2d".

Any idea? :)

Cheers iro

**Comment by irosaurus** [comment]
Hi,
I also tried to configure with --with-maxbuf=16384 but still the same issue as mentioned above.
I would really appreciate any help.
Cheers iro

**Comment by goochjj** [comment]
Try stage_for_upstream/v2.7f

**Comment by irosaurus** [comment]
It's working with 2.7f now, thank you very much!
Cheers iro
