### ISSUE TITLE
Regex too strict in config.c

### ISSUE THREAD

**Issue by adn77** [goochjj/pound#11]
Thanks for the great work and sorry for posting here - I am to lazy to sign up for the mailing list.

Using one of the newer options (Disable SSLv3), made me wonder why it didn't work...
My Config File had everything lined up nicely - in this case using two tab-stops.

``` patch
-    || regcomp(&DisableProto, "^[ \t]*Disable[ \t](SSLv2|SSLv3|TLSv1|TLSv1_1|TLSv1_2)[ \t]*$", REG_ICASE | REG_NEWLINE | REG_EXTENDED)
+    || regcomp(&DisableProto, "^[ \t]*Disable[ \t]+(SSLv2|SSLv3|TLSv1|TLSv1_1|TLSv1_2)[ \t]*$", REG_ICASE | REG_NEWLINE | REG_EXTENDED)
```

**Comment by goochjj** [comment]
Thanks!
