### ISSUE TITLE
Pound 2.7 or 2.8 PCI DSS

### ISSUE THREAD

**Issue by gschoenberger** [goochjj/pound#12]
Hi goochjj,

we are currently using your PCIDSS compliant pound:
- https://github.com/goochjj/pound/commits/pcidss/v2.6
  Is there any newer version than 2.6 (like 2.7 or 2.8) containing the SSL/TLS patches?

Thanks a lot for your great work!
Cheers, Georg

**Comment by goochjj** [comment]
2.7 is the newest version.  The patches in the pcidss/v2.6 branch should not be necessary on 2.7, because they're either outright backports or they're solved in a different way in upstream.
