### ISSUE TITLE
RewriteLocation creates trouble even disabled

### ISSUE THREAD

**Issue by addison74** [goochjj/pound#14]
I am using Pound in this configuration for a dedicated server:

Pound (IP_EXT, Ports 80, 443) => 
Varnish (LOCALHOST, Port 8090) => 
Apache (LOCALHOST, Port 8080)

Pound is dealing with SSL Offloading and Apache has SSL module disable. Our website is using Magento CE 1.9.2.2 which can allow in part or full the frontend secured. We decided to use SSL in frontend only for secured pages like customer accounts, checkout. All the other pages in frontend are using http protocol, unsecured.

Magento can deal sessions using cookies or strings in URL. I have an issue getting sometimes this string ___SID=U where U means unsecured when visiting some links or switching for secured to unsecured parts of Magento. I tried finding a solution and finally discovered the problem in Pound. By default RewriteLocation is set to 1. Changing RewriteLocation to 0 in ListenHTTP and ListenHTTPS I see positive results but only for a small period of time. URLs having string ___SID=U are coming back.

Pound is installed from Debian repository, version 2.6. I searched the Internet for solutions and someone said I have to build pound by myself from source but commenting two lines in svn.c:

``` php
 /*|| strcasecmp(proto, (lstn->ctx == NULL)? "http": "https" */
```

Do you think this will work in my case or I have to give up for Nginx dealing with SSL in front of Varnish? It is clear to me pound creates confusion for Magento which has to insert sessions in URLs.

**Comment by addison74** [comment]
Here is my Pound configuration:

``` html
ListenHTTP
    Address SERVER_IP_ADDRESS
    Port 80
    RewriteLocation 0
    xHTTP 2
    Service
        BackEnd
             Address 127.0.0.1
             Port 8090
        End
    End

ListenHTTPS
    Address SERVER_IP_ADDRESS
    Port 443
    Cert "/home/magento/magento-ssl.pem"
    Ciphers "EECDH+AESGCM:EDH+AESGCM:ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-$
    RewriteLocation 0
    AddHeader "Ssl-Offloaded: on"

    xHTTP 2
    ## allow PUT and DELETE also (by default only GET, POST and HEAD)?:
    #xHTTP 0

    Service
        BackEnd
            Address 127.0.0.1
            Port 8090
        End
    End
End
```

**Comment by addison74** [comment]
Question 1: Shall I set in this case RewriteLocation in both Listens to 2?
Question 2: Shall I use also RewriteDestination to 1?

Thank you.

**Comment by goochjj** [comment]
There's a lot here, but not much detail.
1) I don't maintain pound, and the maintainer doesn't frequent Github.  Per pound's website (www.apsis.ch/pound), you should be asking for help on the Pound mailing list.
That said
2) If you're going to compile your own, you should probably be using the most stable version, 2.7.
3) RewriteDirection is not an option in Pound, as far as I can see, in any version.
4) RewriteLocation of 0 does in fact, disable rewriting.  I've seen nothing to believe it doesn't disable rewriting, my experience is that it does, in fact, work properly, and a quick look at the code seems to confirm this.  So while it is clear to you that pound is causing this problem... It is not clear to me.

I'm further guessing the post you found was this one:
http://comments.gmane.org/gmane.comp.web.pound.general/7149

Where I indicate the fix you've referenced - however,  this only changes the behavior of RewriteLocation when enabled... And in your case, the same backend is used for SSL and non-SSL termination... So RewriteLocation 0 may be the answer.  It may not, if your backend is returning a location of http://127.0.0.1, that is certainly wrong, and you need to deal with it, either in pound, or in your backend.  As you're injecting a header for the backend to process, it should be able to generate proper locations on its own.

RewriteLocation in particular will only ever change the host and port part of the url. (And protocol)  It won't do anything to appended URL variables, paths of the request, or anything else.  So it won't change your __SID variable in any way.

This doesn't look like an actionable issue with pound.  I'm unclear with what you're trying to accomplish, and what problem you're actually having.  Your logged issue seems to be that rewritelocation is acting on requests it shouldn't (i.e. RewriteLocation 0), and your config seems to confirm this... But I see nothing that indicates RewriteLocation is active in that configuration.  On the other hand, you reference a change that would only happen if RewriteLocation > 0 , and for all I know might solve your problem, but only you can try that and determine it.  What's absent is the actual problem - when things work, what is done right?  When things don't work, what is actually wrong?

And it seems based on this:
https://github.com/nexcess/magento-turpentine/issues/980
That you've already determined the appropriate course of action.... so what has changed?

My suggestion is to bring this up on the pound mailing list, including the part which is missing right now - which is the actual HTTP conversation.  (i.e. full HTTP request and matching response)  Ideally, you need to full HTTP request and matching response from each part of the chain... To/From pound, To/from Varnish, and To/From Apache.  I've always used something like this https://ws.apache.org/tcpmon/

Then you can indicate exactly what the Location header was, and what Pound rewrote it to, and why that was bad in your environment... and given that information, someone on the list can help you.
