### ISSUE TITLE
Disable TLS v1.0

### ISSUE THREAD

**Issue by Mattz0r** [goochjj/pound#17]
Hello,

Please can you tell me if it is possible to disable the TLS v1.0 protocol, like you can with DisableSSLv2 and v3?

Thanks!

Matt

**Comment by nyov** [comment]
In newer Pound ([since v2.7d](https://github.com/goochjj/pound/blob/upstream/v2.7d/CHANGELOG#L7)) upstream has added this option as `Disable` (DisableProto) which obsoletes `DisableSSLv2`:


> **Disable** SSLv2|SSLv3|TLSv1|TLSv1_1|TLSv1_2
>
> Disable the protocol **and all lower protocols as well**.  This is due to a limitation in OpenSSL, which does not support disabling a single protocol. For example, `Disable TLSv1` would disable SSLv2, SSLv3 and TLSv1, thus allowing only TLSv1_1 and TLSv1_2.
