### ISSUE TITLE
2.6 pci dss does not find crypto lib with --with-ssl config parameter

### ISSUE THREAD

**Issue by totallyeviljake** [goochjj/pound#7]
I can build 2.7c with --with-ssl=../foo but the 2.6 pcidss branch will not find the crypto library during the configuration build:

./configure --with-ssl=../openssl-0.9.8zc
checking for socket in -lsocket... no
checking for hstrerror in -lresolv... no
checking for BIO_new in -lcrypto... no
Missing OpenSSL (-lcrypto) - aborted

It also does it with the latest openssl-1.0.1j (same error)

**Comment by totallyeviljake** [comment]
Note that version 2.5 does work with the --with-ssl=../openssl-0.9.8zc config parameter. Only 2.6 has this problem.

**Comment by goochjj** [comment]
Probably best to post this to the pound list pound@apsis.ch for that... I
don't have the autoconf source so I can't really fix that.
