### ISSUE TITLE
Build fails with the SCSV patch

### ISSUE THREAD

**Issue by gjedeer** [goochjj/pound#9]
I'm building with openssl-1.0.1j. The error is:

```
http.c: In function ‘do_http’:
http.c:920: error: ‘con’ undeclared (first use in this function)
http.c:920: error: (Each undeclared identifier is reported only once
http.c:920: error: for each function it appears in.)
```

As far as I understand the code base, the first argument should be "be_ssl" (or "ssl", but I guess this variable is not relevant in the backend context).

**Comment by goochjj** [comment]
be_ssl

Sorry when I last compiled I didn't have a library available with SCSV.

Give it a try now please!
Joe

**Comment by gjedeer** [comment]
Now it works. Thank you!
